docs: update ADR-005 on cryptographic equivocation verifcation
cosmos/interchain-security pull request #1022
Opened 2023-06-15 13:25 UTC by sainoe

## Description

The slashing limitation of the upcoming ADR-005 requires some clarifications.

Closes: #1010

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct `docs:` prefix in the PR title
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] reviewed "Files changed" and left comments if necessary 
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] Confirmed the correct `docs:` prefix in the PR title
- [ ] Confirmed all author checklist items have been addressed 
- [ ] Confirmed that this PR only changes documentation
- [ ] Reviewed content for consistency
- [ ] Reviewed content for spelling and grammar
- [ ] Tested instructions (if applicable)
- [ ] Checked that the documentation website can be built and deployed successfully (run `make build-docs`)

2023-06-15 16:48 UTC, mpoke requested changes

2023-06-15 16:48 UTC, mpoke commented on docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md
> +- We currently can't derive an infraction height from the evidence, so it is only possible to tombstone validators, not actually slash them. To explain the technical reasons behind this limitation, l
nit: split into multiple lines to make reviewing easier

2023-06-15 16:48 UTC, mpoke commented on docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md
> +- We currently can't derive an infraction height from the evidence, so it is only possible to tombstone validators, not actually slash them. To explain the technical reasons behind this limitation, l
```suggestion
- We cannot derive an infraction height from the evidence, so it is only possible to tombstone validators, not actually slash them.
  To explain the technical reasons behind this limitation, let's recap the initial [consumer initiated slashing logic](https://github.com/cosmos/ibc/blob/2aa283d4bc8b747cbb860c0f94389d7a62bb802b/spec/app/ics-028-cross-chain-validation/overview_and_basic_concepts.md#consumer-initiated-slashing). 
  In a nutshell, consumer heights are mapped to provider heights through `VSCPackets`, namely through the so called `vscIDs`. 
  When an infraction occurs on the consumer, a `SlashPacket` containing the `vscID` obtained from mapping the consumer infraction height is sent to the provider. 
  Upon receiving the packet, the provider maps the consumer infraction height to a local infraction height, which is used to slash the misbehaving validator. 
  In the context of untrusted consumer chains, all their states, including `vscIDs`, could be corrupted and therefore cannot be used for slashing purposes.
```

2023-06-15 16:48 UTC, mpoke commented on docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md
> +- We currently can't derive an infraction height from the evidence, so it is only possible to tombstone validators, not actually slash them. To explain the technical reasons behind this limitation, l
I would drop the proposed solution to this 3rd limitation from this ADR as it doesn't work. The first iteration should just jail. Then, we can try to figure out a way how to enable slashing. Could you please open an issue stating the problem and add this proposed solution there as a point to start. The issue should be tracked by https://github.com/cosmos/interchain-security/issues/732

2023-06-16 19:43 UTC, jtremback commented on docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md
> +  In the context of untrusted consumer chains, all their states, including `vscIDs`, could be corrupted and therefore cannot be used for slashing purposes.
Further, it would be ideal to completely eliminate the slash packets since we cannot trust them anyway.

2023-06-16 19:45 UTC, merged