(draft) Staking hook integration
cosmos/interchain-security pull request #21
Opened 2021-11-17 00:50 UTC by jtremback

These are my changes to support integration with the staking module unbonding hooks. This mechanism allows CCV to stop certain delegations from unbonding if the unbonding period on any relevant consumer chains has not yet elapsed.

It's still in draft because it is not unit tested, but it doesn't break anything

2021-11-23 11:26 UTC, AdityaSripal requested changes
initial pass review.

Main points:
- Let's use the sequence in IBC instead of storing our own index
- We definitely should not be storing a redundant sequence in the packet data
- Remove registryKeeper. See #23

2021-11-23 11:26 UTC, AdityaSripal commented on x/ccv/parent/keeper/keeper.go
>  		registryKeeper:   registryKeeper,
Pull #23 into this PR, and remove registryKeeper

2021-11-23 11:26 UTC, AdityaSripal commented on x/ccv/parent/keeper/relay.go
>  	k.registryKeeper.UnbondValidators(ctx, chainID, data.ValidatorUpdates)
Remove this line

2021-11-23 11:26 UTC, AdityaSripal commented on x/ccv/parent/module.go
> +	am.keeper.IncrementValidatorSetUpdateId(ctx)
Again this shouldn't be necessary since there is already an index that increments on every packet sent

2021-11-29 22:33 UTC, jtremback commented
Discussed @AdityaSripal's comments on a call:

- `valset_update_id` is currently the same as the packet sequence, and so could be eliminated, but if any other packet types were added into the protocol, it would break.
- UnbondingDelegationEntry could be renamed, but it is a record of the same logical entity as the one in staking, and they will have a 1-1 relationship, so it makes sense for the to have the same name

These changes are now in #24

2021-11-29 22:33 UTC, closed without merging