Move e2e tests to independent folder
cosmos/interchain-security pull request #297
Opened 2022-08-24 17:26 UTC by smarshall-spitzbart

Closes #219

2022-08-25 08:05 UTC, mpoke requested changes
Nice work @smarshall-spitzbart. I didn't check the functionality, since I guess it's just a refactoring, right? 

At the moment the structure is a bit hard to follow, maybe a README.md would help, i.e., 
- `setup_test.go` -- setup for the e2e tests
- `common_test.go` -- helper functions
- `channel_init_test.go` -- e2e tests for the _Channel Initialization_ sub-protocol
- `valset_update_test.go` -- e2e tests for the _Validator Set Update_ sub-protocol
- `unbonding_test.go` -- e2e tests for the _Completion of Unbonding Operations_
- `slashing_test.go` -- e2e tests for the _Consumer Initiated Slashing_ sub-protocol
- `distribution_test.go` -- e2e tests for the _Reward Distribution_ sub-protocol
- `stop_consumer_test.go` -- e2e tests for the _Consumer Chain Removal_ sub-protocol

Move to `valset_update.go` the content from `bonding_test.go` and `vsc_test.go`. 

Move to `channel_init_test.go` the content from `genesis_test.go`, `ibc_test.go`, `history_test.go`, `proposal_test.go`.

`distribution_test.go` will be empty for now. 

Re. the 4 different `...TestSuite`s data structure, I think we can have only one, but let's do that in a separate PR.

2022-08-25 22:16 UTC, smarshall-spitzbart commented
> Nice work @smarshall-spitzbart. I didn't check the functionality, since I guess it's just a refactoring, right?
> 
> At the moment the structure is a bit hard to follow, maybe a README.md would help, i.e.,
> 
> * `setup_test.go` -- setup for the e2e tests
> * `common_test.go` -- helper functions
> * `channel_init_test.go` -- e2e tests for the _Channel Initialization_ sub-protocol
> * `valset_update_test.go` -- e2e tests for the _Validator Set Update_ sub-protocol
> * `unbonding_test.go` -- e2e tests for the _Completion of Unbonding Operations_
> * `slashing_test.go` -- e2e tests for the _Consumer Initiated Slashing_ sub-protocol
> * `distribution_test.go` -- e2e tests for the _Reward Distribution_ sub-protocol
> * `stop_consumer_test.go` -- e2e tests for the _Consumer Chain Removal_ sub-protocol
> 
> Move to `valset_update.go` the content from `bonding_test.go` and `vsc_test.go`.
> 
> Move to `channel_init_test.go` the content from `genesis_test.go`, `ibc_test.go`, `history_test.go`, `proposal_test.go`.
> 
> `distribution_test.go` will be empty for now.
> 
> Re. the 4 different `...TestSuite`s data structure, I think we can have only one, but let's do that in a separate PR.

You're correct that I didn't change any test functionality in this PR, I only moved things around. 

Your mentioned file organization sounds great to me, thank you! My only correction to your proposed solution is that I believe ```TestTrackHistoricalInfo``` should go in its own file under ```normal_operations_test.go```, since it doesn't relate to channel initialization. A new readme was added to the e2e test directory.

Lastly I've opened #300 to address the fact that we have a lot of redundant code in ```setup_test.go```.

2022-08-26 07:33 UTC, mpoke approved these changes
Great work.

2022-08-26 22:13 UTC, jtremback commented on e2e-tests/valset_update_test.go
> +func (s *ProviderTestSuite) TestPacketRoundtrip() {
maybe put this in normal_operations_test

2022-08-26 22:17 UTC, jtremback commented on .github/workflows/automated-tests.yml
>          run: ls
Pretty sure this can be removed and i left it in here from debugging

2022-08-26 22:17 UTC, jtremback approved these changes

2022-08-26 22:56 UTC, merged