Redelegation integration tests
cosmos/interchain-security pull request #312
Opened 2022-08-30 17:44 UTC by smarshall-spitzbart

Closes https://github.com/cosmos/interchain-security/issues/255, also adds a corresponding e2e test

2022-08-31 00:04 UTC, jtremback approved these changes
Nice. You got some e2e tests for the functionality in there too?

2022-08-31 00:09 UTC, smarshall-spitzbart commented
> Nice. You got some e2e tests for the functionality in there too?

Yea I added a single ```TestRedelegationNoConsumer``` e2e test. The equivalent e2e test with a consumer shouldn't be crazy hard to implement, but I left it as a TODO for now

2022-08-31 10:04 UTC, mpoke requested changes
The integration tests LGTM. Some comments below re. the e2e tests.

2022-08-31 10:04 UTC, mpoke commented on e2e-tests/valset_update_test.go
> +}
`TestRedelegationNoConsumer` should also check that after the unbonding period passes on the provider, the redelegation entry is no longer there. Use `TestUnbondingNoConsumer` as an example.

2022-08-31 10:04 UTC, mpoke commented on e2e-tests/valset_update_test.go
> +	// TODO
Use `TestUndelegationProviderFirst` or `TestUndelegationConsumerFirst` as examples.

2022-08-31 20:37 UTC, smarshall-spitzbart commented on e2e-tests/common_test.go
> +	s.Require().Equal(s.providerCtx().BlockHeader().Time.Add(providerUnbondingPeriod), completionTime)
Good catch, I've added a case that validator being UNBONDING as well

2022-08-31 20:45 UTC, smarshall-spitzbart commented on e2e-tests/valset_update_test.go
> +func (s *ProviderTestSuite) TestRedelegationNoConsumer() {
Agreed, I've moved these tests. However ```valset_update_test.go``` is pretty related to unbonding, and this makes the distinction between those two files difficult to understand. Anytime there is an unbonding operation, there will be a valset update. 

Maybe we consider consolidating and/or renaming the two files?

2022-08-31 21:25 UTC, merged

2022-09-01 07:27 UTC, mpoke commented on e2e-tests/valset_update_test.go
> +func (s *ProviderTestSuite) TestRedelegationNoConsumer() {
Validator Set Update is the name of the entire subprotocol (see https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/methods.md#validator-set-update). Unbonding it's just a part of it that includes also the modifications done to the Staking module (see https://github.com/cosmos/ibc/blob/main/spec/app/ics-028-cross-chain-validation/methods.md#validator-set-update). All the files in e2e-tests can be named after the subprotocol that is being tested.