Proposal naming refactors
cosmos/interchain-security pull request #354
Opened 2022-09-08 17:05 UTC by smarshall-spitzbart

Changes all instances, comments, methods, etc. such that:

- ```CreateConsumerChainProposal``` (the abstract type) is now ```ConsumerAdditionProposal```
- ```StopConsumerChainProposal``` (the abstract type) is now ```ConsumerRemovalProposal```
- ```StopConsumerChainProposal()``` (the method) is now ```HandleConsumerRemovalProposal()```
- ```CreateConsumerChainProposal()``` (the method) is now ```HandleConsumerAdditionProposal()```

Related to #331

2022-09-08 18:02 UTC, danwt approved these changes
Amazing, I like the changes a lot. You even got in and changed the subtest name strings. Thanks for this.

2022-09-08 19:32 UTC, jtremback commented on x/ccv/provider/client/proposal_handler.go
>  		Use:   "create-consumer-chain [proposal-file]",
This needs to be renamed as well.

2022-09-08 19:37 UTC, jtremback commented on x/ccv/provider/client/proposal_handler.go
>  		Use:   "create-consumer-chain [proposal-file]",
This needs to be changed as well

2022-09-08 19:38 UTC, jtremback requested changes
Proposals are still created on the CLI using `create-consumer-chain`

2022-09-08 21:23 UTC, smarshall-spitzbart commented
> Proposals are still created on the CLI using `create-consumer-chain`

Great catch, the cli command should now look like 
```bash
tx gov submit-proposal consumer-addition <path/to/proposal.json> --from=<key_or_address>
```

Changes in https://github.com/cosmos/interchain-security/pull/354/commits/15d8abc47439d4690251f65d815efb95a6d02bec

2022-09-09 12:16 UTC, sainoe approved these changes
Clean renaming good work 👍

2022-09-20 21:13 UTC, jtremback approved these changes

2022-09-20 21:13 UTC, merged